### ISSUE TITLE
Just stopping by to say thanks!

### ISSUE THREAD

**Issue by mattlorimor** [ka05/py-tda-auth-refresher#1]
And that I feel your pain. Their API auth flow is _bafflingly_ convoluted.

I'd been off-and-on all day today trying to figure out how to do some monthly trades completely automated through the API, but the 90-day timeout was going to make it all pointless. I haven't had a chance to use it yet, but this looks like it solves the problem quite nicely. I can't believe I stumbled across this six days after you threw it up to GitHub.

I just wish they wouldn't have made authing to their API such a mess. Instead, we get to sit here feeling gross.

Obviously, feel free to close this as it's not a real issue.

**Comment by ka05** [comment]
@mattlorimor I couldn't agree more. This is not the right way to do things at all. But its an effective work around. ...at least until they change their 2FA auth web form flow at some point. lol
And thanks for letting me know, Im glad this repo was helpful to you!
